const String adminPhone = "+918427373281";
const String contactNumber = "+919988752741";
const String websiteUrl = "https://www.viptutors.in";
const String googleApiKey = "AIzaSyA2rMtFcSCZNfZhpcrrMDVfVJa_RXUl4xg";
const int autoPostDeleteDateRange = 30;

const List<String> stateList = [
  "Andaman and Nicobar Islands",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "Dadra and Nagar Haveli",
  "Daman and Diu",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Ladakh",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
];

const List<String> preferredClassList = [
  "LKG",
  "KG",
  "UKG",
  "Nursery",
  "1st",
  "2nd",
  "3rd",
  "4th",
  "5th",
  "6th",
  "7th",
  "8th",
  "9th",
  "10th",
  "11th",
  "12th",
  "Dropper",
  "NEET",
  "IIT-JEE Mains",
  "IIT-JEE Advance",
  "CUET",
  "CAT",
  "MAT",
  "SAT",
  "CTET",
  "CLAT",
  "IELTS",
  "TOEFL",
  "ART",
  "Commerce",
  "Humanities",
  "Computer Classes",
  "IT Classes",
  "BCOM",
  "MCOM",
  "BSC",
  "BSC-IT",
  "Software",
  "BCA",
  "MCA",
  "CA",
  "Accounting",
  "CS",
  "BBA",
  "CMA / ICWA",
  "B.Ed",
  "M.Ed",
  "BBS",
  "BMS",
  "BDS",
  "BAMS",
  "MBBS",
  "BHMS",
  "BA",
  "BDA",
  "MA",
  "MBA",
  "MSC",
  "MSC Physics",
  "MSC Chemistry",
  "MSC Maths",
  "BE",
  "B.Tech",
  "M.Tech",
  "LAW & Judiciary",
  "LLB",
  "Hobby",
  "Music",
  "Singing",
  "ROBOTICS",
  "AI",
  "Coding / Programming",
  "Painting / Drawing",
  "Engineering",
  "Medical",
  "Nursing",
  "Anatomy",
  "Biotech",
  "Yoga",
  "Therapy",
  "Mental Therapy",
  "Physical Therapy",
  "Health Care",
  "Counselling",
  "English Spoken",
  "English Literature",
  "Language Classes",
  "SSC",
  "Career Counseller",
  "Banking",
  "Railway",
  "General Preparation",
  "IES",
  "UPSC",
  "State PCS",
  "PG",
  "PHD",
  "B.Architecture",
  "Hotel Management",
  "Agriculture",
  "Bio.Medical",
  "B.Pharma",
  "B.Medicine",
  "B.Statics",
  "Data Science",
  "Cybersecurity",
  "Dentistry",
  "VPA",
  "Engineering Management",
  "Financial Management",
  "Journalism",
  "Mass Communication",
  "Web Designing",
  "Web Development",
  "App Development",
  "Religious Justice",
  "Criminal Justice",
  "Telecommunications",
  "Pharmaceutical Science",
  "Veterinary Science",
  "Associate Degree",
  "Bachelor Degree",
  "Doctorate Degree",
  "Professional Degree",
  "Interior Designing",
  "Fashion Designing",
  "ECE",
  "EEE",
  "Mechanical Engineering",
  "Production Engineering",
  "Civil Engineering",
  "CSE",
  "ITE",
  "Civil Engineering",
  "Petroleum Engineering",
  "Biochemical Engineering",
  "Robotics Engineering",
  "Machine Learning & AI",
  "Astrology",
  "Palmistry Diploma",
  "Microbiology",
  "Aerospace Engineering",
  "Mining Engineering",
  "Marine Engineering",
  "Research",
  "Defence",
  "Diploma",
  "For Junior",
  "For Senior",
  "Certificate Courses",
  "For School.",
  "For Institute.",
  "For Tuition Centre.",
  "Other",
];

const List<String> boardList = [
  "State Board",
  "CBSE Board",
  "IGCSE Board",
  "ICSE Board",
  "IB Board",
  "ISC Board",
  "NIOS Board"
];

const List<String> subjectList = [
  "LKG All Subjects",
  "UKG All Subjects",
  "Nursery All Subjects",
  "1st All Subjects",
  "2nd All Subjects",
  "3rd All Subjects",
  "4th All Subjects",
  "5th All Subjects",
  "6th All Subjects",
  "7th All Subjects",
  "8th All Subjects",
  "9th All Subjects",
  "10th All Subjects",
  "English",
  "Hindi",
  "SST",
  "Maths",
  "Science",
  "EVS",
  "Painting",
  "Drawing",
  "Art & Craft",
  "Vedic Maths",
  "Abacus",
  "Computer",
  "Information Practices",
  "Instrumental Music",
  "Vocal Music",
  "Dance",
  "French",
  "Physics",
  "Chemistry",
  "Computer Science",
  "Biology",
  "Physical Education",
  "Phonics Sound",
  "Accountancy",
  "Business Studies",
  "Economics",
  "Psychology",
  "Political Science",
  "Home Science",
  "Public Administration",
  "Legal Studies",
  "Mass Media Studies",
  'Entrepreneurship',
  "Human Rights",
  "General Studies",
  "General Science",
  "General Knowledge",
  "Mental Maths",
  "Reasoning",
  "Tally",
  "MS Office",
  "Navodaya School Preparation",
  "Sainik School Preparation",
  "Airforce Preparation",
  "Navy Preparation",
  "Army Preparation",
  "Geography",
  "Fine Arts",
  "History",
  "Sociology",
  "Philosophy",
  "Chess",
  "Rubik’s Cube",
  "Sanskrit",
  "Punjabi",
  "German",
  "Spanish",
  "Japanese",
  "Arabic",
  "Bengali",
  "Chinese",
  "Marathi",
  "Gujarati",
  "Irish",
  "Italian",
  "Kashmiri",
  "Korean",
  "Latin",
  "Urdu",
  "Embedded C",
  "C",
  "C++",
  "JAVA",
  "Coding",
  "Programming Language",
  "Dotnet",
  "Tally",
  "MS Office",
  "CAD",
  "GRE",
  "Preply",
  "Tamil",
  "Telugu",
  "Art",
  "Yoga",
  "Music",
  "Keyboard",
  "Tabla",
  "Gitter",
  "Sitter",
  "Bina",
  "Biotech.",
  "Biochemistry",
  "Anatomy",
  "Medical Subjects",
  "Zoology",
  "Botany",
  "VLSI",
  "Engineering Drawing",
  "Mechanic Eng. Subjects",
  "Electrical Eng. Subjects",
  "Electronic Eng. Subjects",
  "CS Eng. Subjects",
  "IT Eng. Subjects",
  "Production Eng. Subjects",
  "Aeronautical Eng. Subjects",
  "Marine Eng. Subjects",
  "Chemical Eng. Subjects",
  "Civil Eng. Subjects",
  "Petroleum Eng. Subjects",
  "Mining Eng. Subjects",
  "Eng. Maths",
  "Eng. Physics",
  "Eng. Chemistry",
  "Indore Game",
  "Outdore Game",
  "All Subjects",
  "Other",
];
