const String adminPhone = "+918427373281";
const String websiteUrl = "https://www.viptutors.in";
const String googleApiKey = "AIzaSyA2rMtFcSCZNfZhpcrrMDVfVJa_RXUl4xg";

const List<String> stateList = [
  "Andaman and Nicobar Islands",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "Dadra and Nagar Haveli",
  "Daman and Diu",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Ladakh",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
];

const List<String> preferredClassList = [
  "Nursery",
  "Kg",
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "10",
  "11",
  "12",
  "NEET",
  "IIITJEE",
  "ART",
  "Commerce",
  "BCOM",
  "BSC",
  "BCA",
  "CA",
  "BBA",
  "MBA",
  "MSC",
  "MTECH",
  "MUSIC",
  "ROBOTICS / AI",
  "Coding / programming",
  "Painting / Drowning",
  "Engineering",
  "Medical",
  "Yoga",
  "English spoken",
  "Language classes",
  "PG",
  "Diploma",
  "Others",
];

const List<String> subjectList = [
  "English",
  "Hindi",
  "Maths",
  "EVS",
  "Abacus",
  "Computer",
  "Music",
  "Instrumental music",
  "Vocal music",
  "Dance",
  "French",
  "Science",
  "Social Science",
  "Computer",
  "Instrumental music",
  "Physics",
  "Chemistry",
  "Computer Science",
  "Biology",
  "Economics",
  "Physical Education",
  "Accountancy",
  "Business Studies",
  "Economics",
  "Psychology",
  "Political Science",
  "Economics",
  "English",
  "Fine Arts",
  "Psychology",
  "Vocal music",
  "Sociology",
  "Sanskrit",
  "Punjabi",
  "German",
  "French",
  "Spanish",
  "Japanese",
  "Arabic",
  "Bengali",
  "Chinese",
  "Marathi",
  "Gujarati",
  "Irish",
  "Italian",
  "Kashmiri",
  "Korean",
  "Latin",
  "Urdu",
  "Embedded C",
  "C++",
  "C",
  "JAVA",
  "Coding",
  "Programming language",
  "Dotnet",
  "Tally",
  "MS office",
  "CAD",
  "Tamil",
  "Telugu",
  "Music",
  "Keyboard",
  "Tabla",
  "Guitar",
  "Biotech",
  "Medical",
  "Mech Eng. subjects",
  "Electrical eng. subjects",
  "Electronic eng. Subjects",
  "CS eng. Subjects",
  "IT eng. Subjects",
  "Production eng. Subjects",
  "Aronotics eng. Subjects",
  "Marine eng. Subjects",
  "Chemical eng. Subjects",
  "Eng. Maths",
  "Eng. Physics",
  "Eng. Chemistry",
  "Medical subjects",
  "Art and Craft",
  "Kuran"
];
